makes_mapping = {}

makes_mapping['airstream'] = ['air stream', 'airstream rv', 'airsteam']
makes_mapping['ace'] = ['a.c.e.', 'a.c.e']
makes_mapping['aliner'] = ['a-liner', 'a liner', 'aliner`']
makes_mapping['aerolite'] = ['aero-lite', 'aero lite', 'aerolite', 'areolite', 'aero', 'ae']
makes_mapping['alliance'] = ['alliance rv']
makes_mapping['alpenlite'] = ['alpen-lite', 'alpen lite']
makes_mapping['alumcraft'] = ['aluma-craft', 'aluma craft']
makes_mapping['americamp'] = ['ameri camp', 'ameri-camp']
makes_mapping['american'] = ['american coach', 'american coach american', 'american coach-american', 'americana']
makes_mapping['amerilite'] = ['ameri-lite', 'ameri lite', 'amerelite', 'amerlite', 'amerilte', 'ameri - lite']
makes_mapping['adventurer'] = ['adventurer mh', 'adventurer lp (alp)']
makes_mapping['arg'] = ['arg rv']
makes_mapping['augusta'] = ['augusta rv']
makes_mapping['allegro'] = ['allegro mh', 'allegro bus mh']
makes_mapping['allero'] = ['allero mh']
makes_mapping['ar'] = ['ar one', 'ar- one', 'a-r one','ar-one', 'ar-one maxx', 'arone', 'arone maxx', 'ar-1', 'ar-1 maxx',
                'ar maxx', 'ar one maxx', 'ar one max', 'a-r one maxx', 'ar-one-maxx', 'ar-onemaxx', 'a r one max']
makes_mapping['arctic'] = ['arctic fox', 'arctic rv', 'arctic wolf', 'artic fox']

#########################################

makes_mapping['bak'] = ['bak industries']
makes_mapping['baystar'] = ['bay star']
makes_mapping['bigfoot'] = ['big foot', 'bigfoot rv']
makes_mapping['bighorn'] = ['big horn']
makes_mapping['black series'] = ['blackseries', 'black series caravan']
makes_mapping['blackrock'] = ['black rock']
makes_mapping['blackwood'] = ['blackwood rv']
makes_mapping['born free'] = ['bornfree', 'born-free', 'born free']
makes_mapping['braxton creek'] = ['braxton creek', 'braxton creek bushwhacker', 'braxton creek bushwacker', 'braxton creek bx', 'braxton creek lx']
makes_mapping['b touring'] = ['bt', 'bt cruiser', 'b touring cruiser', 'bt cruiser rv', 'btouring']
makes_mapping['basecamp'] = ['base camp']
makes_mapping['big country'] = ['bigcountry']

#########################################

makes_mapping['camplite'] = ['camp-lite', 'camp lite']
makes_mapping['canam'] = ['can-am', 'can am']
makes_mapping['canterbury'] = ['canterbury rv']
makes_mapping['carriage'] = ['carraige', 'carria']
makes_mapping['carrilite'] = ['carri-lite', 'carri lite', 'lite carri', 'carrielite']
makes_mapping['cedar creek'] = ['cedar creek hathaway', 'ceder creek', 'cedar creek silverback']
makes_mapping['chateau'] = ['chateau mh', 'chatau', 'chaetau', 'chaeteau']
makes_mapping['coach entegra'] = ['coach-entrega', 'coachentrega', 'coach entrega', 'coach-entegra', 'coachentegra']
makes_mapping['coach house'] = ['coach-house', 'coachhouse']
makes_mapping['catalina'] = ['caalina']
makes_mapping['coachmen'] = ['coacahmen', 'coachman', 'coachmen rv', 'coachmen apex', 'coachmen catalina', 'coachment',
                    'coachmen clipper', 'coachmen freedom', 'cochmen', 'coachmen prism', 'coachmen pursuit', 'coachmen mh']

makes_mapping['chaparral'] = ['chapparel', 'chaparel', 'chaparell', 'chaparrall', 'chapparral', 'chaparrel', 'chapparell', 'chapparall', 'chapperel','chapparall',
                        'chapperal', 'chaparral lite', 'chaparal', 'chaparall', 'chaparra', 'chapl', 'chapll', 'chapparal']

makes_mapping['coleman'] = ['coleman rv', 'colemen']
makes_mapping['compass'] = ['compass mh', 'compas', 'compas s']
makes_mapping['concord'] = ['concord mh']
makes_mapping['continental cargo'] = ['continental-cargo', 'continentalargo']
makes_mapping['continental coach'] = ['continental-coach']
makes_mapping['crest'] = ['crest liner', 'crestliner']
makes_mapping['crossroads'] = ['crossroad', 'cross road', 'cross roads', 'crossroads cruiser', 'crossroads rv cruiser', 'crossroads rv', 'crossroads zinger']
makes_mapping['cruiser'] = ['crusier', 'cruise', 'cruise rv', 'cruiser rv', 'cruiser fun finder', 'cruiser mpg', 'cruiser radiance', 'cruisers', 'cruser', 'cruiser lite']

makes_mapping['concord'] = ['concorde']
makes_mapping['clipper'] = ['clipper cadet']
makes_mapping['cheyenne'] = ['cheyene']
makes_mapping['champagne'] = ['champagne edition']
makes_mapping['campfire'] = ['campfire edition', 'camperfire']
makes_mapping['couples coach'] = ['couple coach']
makes_mapping['creek side'] = ['creekside', 'creek side series', 'creek side titanium series']
makes_mapping['cougar'] = ['couger', 'cougar x-lite']

#########################################

makes_mapping['damon'] = ['damon motor coach', 'damon rv', 'damon mh']
makes_mapping['dolphin'] = ['dolphin mh']
makes_mapping['doubletree'] = ['double tree', 'doubletree rv']
makes_mapping['drv'] = ['drv luxury suites']
makes_mapping['dutchmen'] = ['dutchman', 'duchmen', 'ducthmen', 'dutchmen rv', 'dutchmentt']
makes_mapping['dutchstar'] = ['dutch star', 'dutchstar mh']
makes_mapping['dynamax'] = ['dynamax mh', 'dynomax', 'dynamax corp']
makes_mapping['destination'] = ['destination series']

#########################################

makes_mapping['eagle'] = ['eagle cap', 'eagl', 'ea', 'eagle mh', 'eagle ht', 'eagle premier', 'eagle super lite']
makes_mapping['east to west'] = ['east to west rv', 'east to west inc']
makes_mapping['echo'] = ['ecko']
makes_mapping['eclipse'] = ['eclipes', 'eclipse rv', 'elipse']
makes_mapping['endeavor'] = ['endeaver', 'endeavor mh', 'endura']
makes_mapping['enduramax'] = ['endura max', 'endura max rv']
makes_mapping['entegra'] = ['entegra coach', 'entegra rv', 'entrega coach', 'entrega rv', 'entrega', 'enterga', 'entrega esteem']
makes_mapping['erwin'] = ['erwin hymer']
makes_mapping['evergreen'] = ['evergreen rv']
makes_mapping['exgo'] = ['ex-go', 'ex go']
makes_mapping['ez'] = ['e-z', 'e z', 'ez-go', 'ezgo']
makes_mapping['elkridge'] = ['elk ridge']
makes_mapping['era'] = ['era mh']

#########################################

makes_mapping['fiesta'] = ['fiesta mh']
makes_mapping['flagstaff'] = ['flagstaff classic', 'flag staff', 'flaggstaff']
makes_mapping['fleetwood'] = ['fleetwood mh', 'fleetoood', 'fleetwood rv', 'fleetwood-c', 'fltwood', 'fleetwood rv']
makes_mapping['forest river'] = ['forest rier', 'forest riv', 'forest river salem', 'forestriver', 'foret river', 'forrest river', 'forst river', 'forest river rv', 'f rest river', 'forest river inc']
makes_mapping['forza'] = ['forza mh']
makes_mapping['four winds'] = ['four wind', 'fourwinds', 'four winds mh', 'four winds rv', 'four winds international', 'four winns', 'fourwinds mh']
makes_mapping['freelander'] = ['freelander mh']
makes_mapping['frontier'] = ['frontier rv']
makes_mapping['fuzion'] = ['fuzioin', 'fusion']
makes_mapping['full house'] = ['fullhouse']
makes_mapping['freedom'] = ['freedom express', 'freedo m', 'freedome', 'freedom express blast', 'freedom elite']

#########################################

makes_mapping['gearbox'] = ['gear box']
makes_mapping['genesis'] = []
makes_mapping['georgetown'] = ['georgetown mh', 'georgetwn', 'george town', 'georgetown xl']
makes_mapping['glacier'] = ['glacier bay', 'glacier rv', 'glacier bay rv']
makes_mapping['glendale'] = ['glendale rv']
makes_mapping['grand design'] = ['gran design', 'grand', 'gr', 'grand d', 'grand de', 'grand desgn', 'grand desi', 'grand desig',
                            'grand designs', 'grand desing', 'granddesign']

makes_mapping['grand tour'] = ['grand touring', 'grandtouring', 'grand tourer', 'grandtour', 'gt series', 'grand touring series']
makes_mapping['granville'] = ['granville toyota']
makes_mapping['great west'] = ['great west vans']
makes_mapping['gulf stream'] = ['gluf stream', 'gulf stream rv', 'glufstream', 'gulfstream', 'gulf strem']
makes_mapping['grey wolf'] = ['greywolf', 'gray wolf', 'graywolf']
makes_mapping['greyhawk'] = ['grey hawk', 'gray hawk', 'grayhawk']

#########################################

makes_mapping['harley davidson'] = ['harley-davidson']
makes_mapping['heartland'] = ['heart land', 'heartland rv', 'heartland sundance']
makes_mapping['hi-lo'] = ['hi lo', 'hilo']
makes_mapping['hideout'] = ['hide out', 'hideput']
makes_mapping['highland'] = ['highland ridge', 'highland ridge rv', 'highland rv', 'highlander', 'higlander']
makes_mapping['hitchhiker'] = ['hitchhike', 'hitch hike', 'hitch hiker', 'hitchiker']
makes_mapping['holiday'] = ['holiday rambler', 'hol ramb allied', 'holiday rambler mh']
makes_mapping['honda'] = ['honda civic']
makes_mapping['heritage glen'] = ['hrtge glen', 'heratage glen', 'heritage']
makes_mapping['hummingbird'] = ['humming bird']
makes_mapping['hurricane'] = ['hurricane mh', 'huricane']
makes_mapping['hy-line'] = ['hyline']
makes_mapping['hymer'] = ['hymer mh']
makes_mapping['hyperlite'] = ['hyper lite', 'hyper-lite', 'hyper lyte', 'hyperlyte']
makes_mapping['hill country'] = ['hillcountry']

#########################################

makes_mapping['imagine'] = ['image']
makes_mapping['indian'] = []
makes_mapping['impact'] = ['impact trailers']
makes_mapping['intech'] = ['in tech', 'intech rv', 'intechrv']
makes_mapping['innovator'] = ['innovator rv']
makes_mapping['intruder'] = ['intruder mh']
makes_mapping['international'] = ['intl', 'internationa']

#########################################

makes_mapping['jamboree'] = ['jamboree mh']
makes_mapping['jay feather'] = ['jayfeather', 'j feather']
makes_mapping['jay flight'] = ['jayflight', 'j ay flight', 'jayflgiht', 'jflight']
makes_mapping['jayco'] = ['jayc0', 'jaco', 'jayco mh', 'jayco inc']
makes_mapping['jumping jack'] = ['jumper jack', 'jumping-jack']

#########################################

makes_mapping['k-z'] = ['k-z inc', 'kz', "k - z", 'k/z', 'k- z', 'k -z', 'k z', 'kx', 'kz rv', 'kz-rv', 'kzrv', 'k-z rv']
makes_mapping['keystone'] = ['keysone rv', 'keystone rv', 'kestone', 'keysone', 'keytone']
makes_mapping['kencraft'] = ['ken-craft', 'ken craft']
makes_mapping['king of the road'] = ['king/road', 'king road']
makes_mapping['kioti'] = []
makes_mapping['kubota'] = []

#########################################

makes_mapping['leisure'] = ['leisure travel', 'leisure vans', 'leisure van', 'leisure time']
makes_mapping['leprechaun'] = ['leprechaun mh', 'lephrechaun', 'leprachaun', 'lepreachan', 'leprechuan']
makes_mapping['lexor'] = ['lexor mh']
makes_mapping['liberty'] = ['liberty coach', 'liberty outdoors']
makes_mapping['lifestyle'] = ['lifestyle rv', 'lifestyle luxury rv']
makes_mapping['light way'] = ['lightway', 'lite way']
makes_mapping["livin'lite"] = ["livin' lite", "livin lite", "livin’ lite rv", "Livin™"]
makes_mapping["look"] = ["look trailers"]
makes_mapping['lp'] = ['lp (alp)']
makes_mapping['lantern'] = ['lantern lt', 'lantern light']
makes_mapping['light'] = ['light lx', 'ligh t']
makes_mapping['lexus'] = []
#########################################

makes_mapping['mandalay'] = ['mandalay coach']
makes_mapping['mercedes'] = ['mercedes-benz']
makes_mapping['meridian'] = ['meridian mh']
makes_mapping['mesa'] = ['mesa ridge']
makes_mapping['mh'] = ['motor homes', 'motorhomes', 'motor home', 'motorhome']
makes_mapping['micro'] = ['micro lite', 'microlite', 'micro-lite', 'micro boost']
makes_mapping['minnie'] = ['mini', 'minni', 'minnie mh', 'minnie winnie', 'minniwinni', 'minnie tt', 'minnie plus', 'minnie drop', 'minnielite', 'minnie lite']
makes_mapping['monaco'] = ['monaco rv', 'monacoi']
makes_mapping['montego'] = ['montego bay']
makes_mapping['mountain'] = ['mountain aire', 'mountainaire']
makes_mapping['mt. mckinley'] = ['mt mckinley']
makes_mapping['mvp'] = ['mvp rv']
makes_mapping['manufacturing'] = ['mfg', 'maufacturing']

makes_mapping['national'] = ['national rv']
makes_mapping['nissan'] = ['nisssan']
makes_mapping['new horizon'] = ['new horizons']
makes_mapping['newmar'] = ['new mar', 'new-mar']
makes_mapping['nexus'] = ['nexus rv', 'nexxus']
makes_mapping['no boundaries'] = ['nobo', 'no bo', 'no-bo', 'noboundaries']
makes_mapping['northwood'] = ['norhwood', 'northwood manufacturing', 'northwood manufactureing', 'northwood mfg', 'northwoods', 'nrwd']
makes_mapping['northpeak'] = ['north peak']
makes_mapping['northpoint'] = ['north point']
makes_mapping['northshore'] = ['north shore']
makes_mapping['northtrail'] = ['north trail', 'northrtail']
makes_mapping['northern'] = ['northern lite']
makes_mapping['northland'] = ['north land']
makes_mapping['nucamp'] = ['nu camp', 'nu-camp', 'nucamp rv']
makes_mapping['nu-wa'] = ['nu wa', 'nuwa', 'nuway']

#########################################

makes_mapping['open range'] = ['open range rv', 'openrange']
makes_mapping['open road'] = ['open road mh']
makes_mapping['outdoor'] = ['outdoors', 'outdoor rv', 'outdoors rv', 'out doors', 'out door']
makes_mapping['outlook'] = ['outlook mh', 'out look']

#########################################

makes_mapping['pace'] = ['pace american']
makes_mapping['pacific'] = ['pacific coach', 'pacific coachworks', 'pacific coach works', 'pacific coachwo', 'pacificcoachwor', 'pacifica', 'pacificiks']
makes_mapping['palomino'] = ['palamino', 'palimino', 'palmino', 'palomina', 'palomi', 'polomino']
makes_mapping['past time'] = ['pasttime', 'pastime']
makes_mapping['path finder'] = ['pathfinder']
makes_mapping['performance'] = ['perfo']
makes_mapping['peterson'] = ['peterson industries', 'peterson ind']
makes_mapping['phaeton'] = ['phaeton mh', 'phateon']
makes_mapping['phoenix'] = ['phoenix cr', 'phoenix cruiser', 'phoenix usa cruiser', 'phoenix lite', 'pheonix']
makes_mapping['play mor'] = ['playmor', 'play-mor', 'play mor rv']
makes_mapping['pilgrim'] = ['pilgrim international']
makes_mapping['pleasant'] = ['pleasant valley', 'pleasant vally']
makes_mapping['pleasure way'] = ['pleasure-way', 'pleasureway']
makes_mapping['potomac'] = ['potomac rv']
makes_mapping['prime time'] = ['primetime', 'prime time rv', 'primetime rv']
makes_mapping['prism'] = ['prism mh', 'prism elite', 'prisim']
makes_mapping['palazzo'] = ['palazo', 'Pallazo', 'pallazo']
makes_mapping['pursuit precision'] = []
makes_mapping['prestige'] = ['prestig e', 'prestge', 'presti ge']

#########################################

makes_mapping['quicksilver'] = ['quick silver']

#########################################

makes_mapping['r vision'] = ['r-vision', 'rvision']
makes_mapping['r pod'] = ['r-pod', 'rpod', 'r.pod']
makes_mapping['rc'] = ['rc industries', 'rc trailers', 'rstch']
makes_mapping['recreation'] = ['recreation by design']
makes_mapping['rexhall'] = ['raxhall', 'rexall']
makes_mapping['redwood'] = ['redwood rv', 'red wood']
makes_mapping['regency'] = ['regency rv']
makes_mapping['renegade'] = ['renegade rv', 'renegae']
makes_mapping['riverside'] = ['riverside rv', 'river side']
makes_mapping['revolution'] = ['revolution mh', 'revolution le']
makes_mapping['roadtrek'] = ['road trek', 'roadtrek mh']
makes_mapping['rockwood'] = ['rock wood', 'rockwoord', 'rockwoodd', 'rookwood']
makes_mapping['royal'] = ['royals']
makes_mapping['rev'] = ['rev group']
makes_mapping['ranger'] = ['ranger mh']
makes_mapping['reflection'] = ['refelction', 'refelection', 'reflections', 'reflecion']

#########################################

makes_mapping['s&s'] = ['s & s', 's&s campers']
makes_mapping['shadow'] = ['shadow cruiser', 'shadow trailer']
makes_mapping['shasta'] = ['shasta rvs', 'shasta rv']
makes_mapping['show hauler'] = ['showhauler']
makes_mapping['siesta'] = ['siesta mh']
makes_mapping['sightseer'] = ['sightseer mh']
makes_mapping['skyline'] = ['skline']
makes_mapping['snow river'] = ['snowriver']
makes_mapping['solei'] = ['solei mh']
makes_mapping['solaris'] = ['solis']
makes_mapping['spirit'] = ['spirit of american', 'sprit']
makes_mapping['sportscoach'] = ['sports coach mh', 'sportcoach']
makes_mapping['sportsmen'] = ['sportsman', 'sporstmen', 'sportsmn']
makes_mapping['sport trek'] = ['sporttrek', 'spor trek', 'sporttrek touring edition']
makes_mapping['sportsmobile'] = ['sports mobile']
makes_mapping['springdale'] = ['springale', 'springdale mini', 'springdale ss']
makes_mapping['starcraft'] = ['star craft', 'starcraft ar', 'starcraft rv', 'starcraft']
makes_mapping['storm'] = ['storm mh']
makes_mapping['sunlight'] = ['sun lite', 'sun-lite', 'sunlite', 'sun light']
makes_mapping['sunseeker'] = ['sun seeker', 'sun-seeker']
makes_mapping['sun valley'] = ['sunvalley', 'sun-valley']
makes_mapping['sun catcher'] = ['suncatcher', 'sun-catcher']
makes_mapping['sunsport'] = ['sun sport']
makes_mapping['suncruiser'] = ['sun cruiser']
makes_mapping['sun tracker'] = ['suntracker', 'sun-tracker']
makes_mapping['sunline'] = ['sunliner']
makes_mapping['suzuki'] = []
makes_mapping['stealth enterprises llc'] = []
makes_mapping['sunnybrook'] = ['sunny brook', 'sunny-brook', 'sunnybrook rv']
makes_mapping['sunset'] = ['sunset park rv', 'sunset rv', 'sunset park', 'sunset creek', 'sunset trail']
makes_mapping['sunstar'] = ['sunstar mh', 'sun star']
makes_mapping['sylvan sport'] = ['sylvansport']
makes_mapping['sonic'] = ['sonic lite', 'sonic x']
makes_mapping['see ya'] = ['see-ya', 'seeya', 'see ya mh']
makes_mapping['silverback'] = ['silver back']

#########################################

makes_mapping['tab'] = ['t@b']
makes_mapping['tag'] = ['t@g']
makes_mapping['teton'] = ['teton homes']
makes_mapping['thor'] = ['thor america', 'thor motor coach', 'thor motorcoach', 'thormotor coach','thor industries', 
                'thor industry', 'thor mh', 'thor motor coac', 'thor motor']
makes_mapping['tiffin'] = ['tiffan', 'tiffen', 'tiffin motor homes', 'tiffin motorhomes', 'tiffin motor ho', 'tiffin open roads',
                    'tiffin phaeton', 'tiffin wayfarer', 'ti', 'tiffin mh']
makes_mapping['timeout'] = ['time out']
makes_mapping['tioga'] = ['tioga mh', 'tioga ranger mh']
makes_mapping['topdeck'] = ['top deck']
makes_mapping['trail lite'] = ['trail-lite', 'traillite']
makes_mapping['trail manor'] = ['trail-manor', 'trailmanor', 'trail mannor']
makes_mapping['trail runner'] = ['trail-runner', 'trailrunner']
makes_mapping['trail vision'] = ['trailvision', 'trail-vision']
makes_mapping['trail sport'] = ['trail-sport', 'trailsport']
makes_mapping['transcend'] = ['transend', 'transcned']
makes_mapping['travato'] = ['travato mh']
makes_mapping['travel lite'] = ['travel line', 'travellite', 'travel-lite']
makes_mapping['travel star'] = ['travel-star', 'travelstar']
makes_mapping['travelcraft'] = ['travel-craft', 'travel craft']
makes_mapping['travelmaster'] = ['travel-master', 'travel master']
makes_mapping['triple'] = ['triple e', 'triple-e', 'triple e rv']
makes_mapping['travel supreme'] = ['trvl sprme', 'trvl suprm']
makes_mapping['travel trailer'] = ['tt']
makes_mapping['turtle'] = ['turtle top']
makes_mapping['trail blazer'] = ['trailblazer']
makes_mapping['tailwind'] = ['tailwiind', 'tail wind', 'tail-wind']
makes_mapping['tailgator'] = ['tailgater', 'tail gator']
makes_mapping['track & trail'] = ['track and trail', 'track trail', 'track n trail']

makes_mapping['united'] = ['united trailers']
makes_mapping['universal'] = ['universal trailers']

makes_mapping['vegas'] = ['vegas mh']
makes_mapping['vanleigh'] = ['van leigh', 'vanleigh rv']
makes_mapping['vengeance'] = ['vengence', 'vengance', 'vengenace']
makes_mapping['ventana'] = ['ventana mh', 'ventenna']
makes_mapping['venture'] = ['ventur', 'venture rv', 'ventura']
makes_mapping['view'] = ['viewfinder', 'view finder']
makes_mapping['viva'] = ['viva mh']
makes_mapping['vista'] = ['vista lx', 'vista mh', 'vesta']
makes_mapping['vintage'] = ['vintage trailers']
makes_mapping['voyager'] = ['voyager trailers']
makes_mapping['viking'] = ['vicking']

makes_mapping['wayfarer'] = ['wayfarer mh']
makes_mapping['weekend warrior'] = ['weekend', 'weekender']
makes_mapping['warrior'] = ['warrior rv']
makes_mapping['western'] = ['western rv']
makes_mapping['wildwood'] = ['wild wood', 'wildwoods', 'wilwood']
makes_mapping['windsport'] = ['wind sport', 'winsport']
makes_mapping['winnebago'] = ['winebago', 'winnabago', 'winnbago', 'winneabgo', 'winnibago', 'winniebago', 'winneabo', 'winnebago mh', 'winnabgo', 'winnebego', 'winnienebago']
makes_mapping['winnie'] = ['win', 'winn', 'winni', 'winne drop', 'winni drop', 'winnie drop', 'winnie plus', 'winne']
makes_mapping['wolfpack'] = ['wolf pack', 'wold pack', 'wolf pak']
makes_mapping['wolfpup'] = ['wolf pup']
makes_mapping['white hawk'] = ['whit hawk', 'whitehawk', 'wihtehawk']
makes_mapping['white water'] = ['white-water', 'whitewater', 'whitewater']
makes_mapping['wildcat'] = ['wildcatt', 'wildkat']
makes_mapping['wilderness'] = ['wlderness']

makes_mapping['xalta'] = ['xlata']
makes_mapping['xlite'] = ['x lite', 'x-lite']
makes_mapping['xplor'] = ['xplore', 'xplor2']

makes_mapping['yetti'] = ['industries yetti']
makes_mapping['yellowstone'] = ['yellowstone rv']

makes_mapping['subaro'] = []
makes_mapping['prevost'] = ['prevost mh']
makes_mapping['palanimo'] = []

makes_mapping['alumaweld'] = []
makes_mapping['vespa'] = []
makes_mapping['kymco'] = []
makes_mapping['wellcraft'] = []
makes_mapping['yamaha'] = []
makes_mapping['dells'] = []
makes_mapping['american teardrop'] = []
makes_mapping['arctic cat'] = []
makes_mapping['grand junction'] = []